---

- hosts: localhost
  vars:
    temp_path: /tmp
  pre_tasks:
  - set_fact:
      zip_path: /tmp/kubeConfig-{{ cluster_id }}.zip
      kube_config_path: /tmp/kubeConfig-{{ cluster_id }}
      IC_IAM_TOKEN: "{{ lookup('env','IC_IAM_TOKEN') }}"
      IC_IAM_REFRESH_TOKEN: "{{ lookup('env','IC_IAM_REFRESH_TOKEN') }}"

- name: apply common configuration to all nodes
  hosts: localhost
  roles:
    - role: set-kube-config
    - role: web
    - role: db

